### sklearn.model_selection.StratifiedKFold
* class sklearn.model_selection.StratifiedKFold(n_splits=5, *, shuffle=False, random_state=None)

In [2]:
from sklearn.datasets import load_iris

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold, StratifiedKFold
import numpy as np
iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=5)
cv_accuracy =[]
print('붓꽃 데이터 세트크기 :',features.shape[0])
print(skfold)
for i in skfold.split(features, label):
    print(i)

붓꽃 데이터 세트크기 : 150
StratifiedKFold(n_splits=5, random_state=None, shuffle=False)
(array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149]), array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109]))
(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  20,  21,  22,
 

In [7]:
n_iter=0
for train_index,test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n#{n_iter} 교차검증 정확도 : {accuracy}, 학습데이터크기 : {train_size}, 검증데이터크기 : {test_size}'
            .format(n_iter,accuracy, train_size, test_size))
    print('#{0} 검증세트인덱스:{1}' .format(n_iter, test_index))
    cv_accuracy.append(accuracy)

print('\n## 평균검증 정확도:', np.mean(cv_accuracy))


#1 교차검증 정확도 : 0.9667, 학습데이터크기 : 120, 검증데이터크기 : 30
#1 검증세트인덱스:[  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]

#2 교차검증 정확도 : 0.9667, 학습데이터크기 : 120, 검증데이터크기 : 30
#2 검증세트인덱스:[ 10  11  12  13  14  15  16  17  18  19  60  61  62  63  64  65  66  67
  68  69 110 111 112 113 114 115 116 117 118 119]

#3 교차검증 정확도 : 0.9, 학습데이터크기 : 120, 검증데이터크기 : 30
#3 검증세트인덱스:[ 20  21  22  23  24  25  26  27  28  29  70  71  72  73  74  75  76  77
  78  79 120 121 122 123 124 125 126 127 128 129]

#4 교차검증 정확도 : 0.9667, 학습데이터크기 : 120, 검증데이터크기 : 30
#4 검증세트인덱스:[ 30  31  32  33  34  35  36  37  38  39  80  81  82  83  84  85  86  87
  88  89 130 131 132 133 134 135 136 137 138 139]

#5 교차검증 정확도 : 1.0, 학습데이터크기 : 120, 검증데이터크기 : 30
#5 검증세트인덱스:[ 40  41  42  43  44  45  46  47  48  49  90  91  92  93  94  95  96  97
  98  99 140 141 142 143 144 145 146 147 148 149]

## 평균검증 정확도: 0.9600200000000001


In [8]:
skfold=StratifiedKFold(n_splits=3)
cv_accuracy =[]
print('붓꽃 데이터 세트크기 :',features.shape[0])
print(skfold)
for i in skfold.split(features, label):
    print(i)

붓꽃 데이터 세트크기 : 150
StratifiedKFold(n_splits=3, random_state=None, shuffle=False)
(array([ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  67,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149]), array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]))
(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        

In [9]:
n_iter=0
for train_index,test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n#{n_iter} 교차검증 정확도 : {accuracy}, 학습데이터크기 : {train_size}, 검증데이터크기 : {test_size}'
            .format(n_iter,accuracy, train_size, test_size))
    print('#{0} 검증세트인덱스:{1}' .format(n_iter, test_index))
    cv_accuracy.append(accuracy)

print('\n## 평균검증 정확도:', np.mean(cv_accuracy))


#1 교차검증 정확도 : 0.98, 학습데이터크기 : 100, 검증데이터크기 : 50
#1 검증세트인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차검증 정확도 : 0.94, 학습데이터크기 : 100, 검증데이터크기 : 50
#2 검증세트인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차검증 정확도 : 0.98, 학습데이터크기 : 100, 검증데이터크기 : 50
#3 검증세트인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균검증 정확도: 0.9666666666666667
